### ISSUE TITLE
[Bug?] Ctrl click inspecting mog items from the snipe list

### ISSUE THREAD

**Issue by zeenk** [Auctionator/PointBlankSniper#12]
Don't know if this a bug or something that is not supported for this addon but ctrl + clicking on items in the list does not work to open the dressing room to see what an item on the list looks like, would be nice to have. :)

**Comment by plusmouse** [comment]
Available in the latest alpha, or from here:
[PointBlankSniper-5.1-1-g5ffaee7.zip](https://github.com/Auctionator/PointBlankSniper/files/8749779/PointBlankSniper-5.1-1-g5ffaee7.zip)

**Comment by zeenk** [comment]
Thanks 👍
