### ISSUE TITLE
Lua error

### ISSUE THREAD

**Issue by zeenk** [Auctionator/PointBlankSniper#14]
Message: ...nterface\AddOns\PointBlankSniper\Source\Buy\Main.lua:68: bad argument #1 to 'min' (number expected, got nil)
Time: Wed May 25 16:49:32 2022
Count: 4
Stack: ...nterface\AddOns\PointBlankSniper\Source\Buy\Main.lua:68: bad argument #1 to 'min' (number expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `min'
[string "@Interface\AddOns\PointBlankSniper\Source\Buy\Main.lua"]:68: in function <...nterface\AddOns\PointBlankSniper\Source\Buy\Main.lua:36>

Locals:

**Comment by plusmouse** [comment]
Fixed in the latest alpha (available from Curseforge shortly). You'll see a screen like this when attempting to buy an item that's only available for bidding in the future:
![image](https://user-images.githubusercontent.com/60280559/170775412-9427c710-ec56-458b-862e-8a07f117ddbb.png)
