### ISSUE TITLE
[Lua Error]

### ISSUE THREAD

**Issue by zeenk** [Auctionator/PointBlankSniper#16]
Message: ...nterface\AddOns\PointBlankSniper\Source\Buy\Main.lua:108: attempt to index field 'resultInfo' (a nil value)
Time: Sun May 29 23:54:37 2022
Count: 1
Stack: ...nterface\AddOns\PointBlankSniper\Source\Buy\Main.lua:108: attempt to index field 'resultInfo' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\PointBlankSniper\Source\Buy\Main.lua"]:108: in function `UpdateBuyState'
[string "@Interface\AddOns\PointBlankSniper\Source\Buy\Main.lua"]:71: in function <...nterface\AddOns\PointBlankSniper\Source\Buy\Main.lua:36>

Locals:

**Comment by plusmouse** [comment]
This issue has been fixed in a77f3de615a5cf82e4bb19a58d6f0dda19a84461
