### ISSUE TITLE
Feature Idea: Always scan for specific item(s) regardless of %

### ISSUE THREAD

**Issue by zeenk** [Auctionator/PointBlankSniper#18]
Don't know how hard something like this would be to implement or if it's possible at all but I think it would be pretty nice to have for this addon that you can "white list" specific items, maybe add a button with a list that you can type in the item(s) you want the addon to look out for regarding of what % value you have selected.

For example if you have the % set at 20 and someone posts a Wooly White Rhino for 1.5m the addon would not pick up that sweet deal, or if someone would for whatever reason post a swift spectral tiger for goldcap that would still be huge profit to buy ^^

Or maybe add some sort of option in Auctionator when u edit an item in the shopping list to "Always scan for this in PBS" something like that?

![2022-06-11_18-04-45](https://user-images.githubusercontent.com/68170439/173195664-5fdb36c4-3cb9-43b2-a9ed-20eb8541e0b7.png)

**Comment by plusmouse** [comment]
You can put 10,000,000g (type `10000000`) as the max price, that will ensure its always shown - setting a max price overrides any price determined by the %.

**Comment by zeenk** [comment]
Oh didn't know that thx!
